anguage: cpp
os:
  - linux
compiler:
  - g++
install:
  - sudo pip install codecov
script:
  - make
  - make test
  - make gcov
branches:
  only:
    - master
after_success:
  - codecov -t 79db3637-e2e2-4bb6-9731-41e776ab0de8 -X gcov